#! /bin/sh

CALLBACK_ANDROID_PATH="/usr/local/callbackandroid/"
CONFIG_FILE=".pgt/config"

# default values
TARGET="device"
LOG="debug"
ACTIVITY=$CURRENT_DIRECTORY_NAME
PACKAGE=com.phonegap.$(echo $ACTIVITY | tr '[A-Z]' '[a-z]')
APK="bin/$ACTIVITY-debug.apk"

# specific phonegap config
PHONEGAP=true
PHONEGAP_VERSION="1.3.0"
BUILDER=false
WWW_FOLDER=false

COLOR_ENABLED=1
COLOR_SEPARATOR=$COLOR_BOLD_YELLOW
COLOR_LOG_INFO=$COLOR_BLUE
COLOR_LOG_ERROR=$COLOR_RED
COLOR_LOG_SUCCESS=$COLOR_GREEN