#! /bin/sh

function create
{
	echo "\n""$COLOR_YELLOW""--- CREATE ---""$COLOR_WHITE""/n"

	# folder doesn't exist
	if [[ !(-d android/) ]]; then
		echo "creating android folder..."
		mkdir android
	# if folder not empty, trow error
	elif [[ !(-z $(ls android/)) ]]; then
		echo "Error: folder android must be empty"
		exit
	fi

	echo "Creating PGT folder"
	mkdir android/.pgt
	cd android/.pgt

	echo "Creating PGT config file"

	set_builder
	set_webapp_path
	set_phonegap_final_path

	cd -

	cd $CALLBACK_ANDROID_PATH
	ACTIVITY_NAME=$CURRENT_DIRECTORY_NAME
	PACKAGE_NAME=com.phonegap.$(echo $ACTIVITY_NAME | tr '[A-Z]' '[a-z]')
	./bin/create $CURRENT_DIRECTORY/android $PACKAGE_NAME $ACTIVITY_NAME

	cd -

	echo "Deleting phonegap folder"
	rm -rf android/phonegap

	echo "Deleting readme.md"
	rm android/.phonegap/readme.md
	rm android/.phonegap/android/readme.md

	get_config

	echo "Moving phonegap files"
	mv android/.phonegap/android/phonegap-$VERSION.js android/.phonegap/phonegap-$VERSION.js
	mv android/.phonegap/android/phonegap-$VERSION.jar android/.phonegap/phonegap-$VERSION.jar

	echo "Deleting android/.phonegap/android/"
	rm -rf android/.phonegap/android/

	echo "Android phonegap application created"
}

function set_builder
{
	echo "# # custom builder script before compilation (set to \"no\" to disable)" >> config
	. $PGT_DIRECTORY/builder
	create_custom_builder
	echo "BUILDER=$builder" >> config
}

function set_webapp_path
{
	echo "# directory of the webapp relative to the app root" >> config
	echo "Specify the path to the web app root relative to the app root"
	read webapp_root
	echo "WWW_DIR=$webapp_root" >> config
}

function set_phonegap_final_path
{
	echo "# final phonegap library path in the android app assets" >> config
	echo "Specify the final path where phonegap should be (relative to the android/assets/www/ directory)"
	read phonegap_path
	echo "PHONEGAP_PATH=$phonegap_path" >> config
}