#! /bin/sh

function get_options
{
	# options
	while getopts ":p:t:l:cbdr" opt; do
		case $opt in
			p)
				if [[ !(-d $OPTARG) ]]; then
					echo "Error: application folder $OPTARG doesn't exist"
					exit
				fi
				echo cd $OPTARG
				cd $OPTARG
				;;
			t)
				echo target=$OPTARG
				target=$OPTARG
				;;
			c) create=on;;
			b) build=on;;
			d) deploy=on;;
			r) run=on;;
			l) log=$OPTARG;;
			\?)
				echo "Error: invalid option: -$OPTARG" >&2
				exit 1
				;;
			:)
				echo "Error: option -$OPTARG requires an argument." >&2
				exit 1
				;;
		esac
	done
}