#! /bin/sh

function get_options
{
	# options
	while getopts ":p:t:l:cbdr" opt; do
		case $opt in
			p)
				if [[ !(-d $OPTARG) ]]; then
					log_error "application folder $OPTARG doesn't exist"
					exit
				fi
				echo cd $OPTARG
				cd $OPTARG
				;;
			t)
				target=$OPTARG
				;;
			c) create=on;;
			b) build=on;;
			d) deploy=on;;
			r) run=on;;
			l) log=$OPTARG;;
			\?)
				log_error "invalid option: -$OPTARG"
				exit 1
				;;
			:)
				log_error "option -$OPTARG requires an argument."
				exit 1
				;;
		esac
	done
}