#! /bin/sh

function build
{
	log_action_separator "BUILD"

	# folder android
	check_folder_android

	get_config

	# got a builder?
	if test "${BUILDER+defined}" && [ ${BUILDER} != "no" ]; then
		log_separator
		echo "Launching the custom builder..."
		# check file permission
		if [[ !(-x $BUILDER) ]]; then
			# can't execute the builder
			echo "Adding the necessary rights to the builder"
			chmod u+x $BUILDER
		fi
		./$BUILDER
	fi

	log_separator

	echo "Cleaning android/assets/www"
	# delete wwww
	rm -rf android/assets/www/
	# create www
	mkdir android/assets/www/

	echo "Updating android/assets/www"
	# copy all files in android/assets/www
	cp -r $WWW_DIR/* android/assets/www/

	# adding the .gitignore in the assets folder
	echo .gitignore > android/assets/www/.gitignore
}