#! /bin/sh

function pgt_build
{
	if ${PHONEGAP:=true} ; then

		log_action_separator "BUILD"

		# got a builder?
		if [ ! $BUILDER = false ]; then
			log_separator

			if [ ! -f "$BUILDER" ]; then
				log_error "The custom builder does not exist"
				echo "Use pgt set builder to change the path"
				exit
			fi

			echo "Launching the custom builder..."

			# check file permission
			if [ ! -x $BUILDER ]; then
				# can't execute the builder
				log_info "Adding the necessary rights to the builder"
				chmod u+x $BUILDER
			fi

			./$BUILDER
			log_separator
		fi

		echo "Cleaning assets/www"
		# delete wwww
		rm -rf assets/www/
		# create www
		mkdir assets/www/

		if [ ! $WWW_FOLDER = false ]; then
			echo "Updating assets/www"
			# copy all files in assets/www
			cp -r $WWW_FOLDER/* assets/www/
		fi

	else
		log_info "Not a phonegap project, don't need to build"
	fi
}