#! /bin/sh

# parameteres: COMPIL_MODE debug release 
function pgt_compil
{
	log_action_separator "COMPILATION"

	# bug sdk-16
	# ant clean

	echo "Compilation mode: $COMPIL_MODE" 
	ant $COMPIL_MODE
}