#! /bin/sh

function pgt_create
{
	log_action_separator "CREATE"

	# folder doesn't exist
	if [ ! -d android/ ]; then
		echo "creating android folder..."
		mkdir android
		cd android
	# if folder not empty, trow error
	elif [ ! -z $(ls android/) ]; then
		log_error "Folder android must be empty"
		exit
	fi

	cd $CALLBACK_ANDROID_PATH
	./bin/create $CURRENT_DIRECTORY/android $PACKAGE $ACTIVITY

	# come back to android
	cd -

	echo "Deleting phonegap folder"
	rm -rf phonegap

	echo "Deleting readme.md"
	rm .phonegap/readme.md
	rm .phonegap/android/readme.md

	echo "Moving phonegap files"
	mv .phonegap/android/phonegap-$PHONEGAP_VERSION.js .phonegap/phonegap-$PHONEGAP_VERSION.js
	mv .phonegap/android/phonegap-$PHONEGAP_VERSION.jar .phonegap/phonegap-$PHONEGAP_VERSION.jar

	echo "Deleting .phonegap/android/"
	rm -rf .phonegap/android/

	echo "Cleaning www/assets/"
	rm -rf assets/
	mkdir assets/
	mkdir assets/www/

	# adding a git ignore to ignore directories
	echo .gitignore > .gitignore
	echo assets/www/* >> .gitignore
	echo build/* >> .gitignore
	echo gen/* >> .gitignore

	# create the config file automatically
	. $PGT_DIRECTORY/actions/config
	generate_config

	log_success "Android phonegap application created"
}