#! /bin/sh

function deploy
{
	echo "\n""$COLOR_YELLOW""--- DEPLOY ---""$COLOR_WHITE""\n"

	check_folder_android

	get_config
	get_target

	echo "Installing on $target..."
	adb $targetoption install -r android/bin/$ACTIVITY-debug.apk
}