#! /bin/sh

function pgt_run
{
	log_action_separator "RUN"

	get_target

	echo "Starting $PACKAGE/$PACKAGE.$ACTIVITY..."

	# TODO check if the activity exists

	start=$(adb $targetoption shell am start -n $PACKAGE/$PACKAGE.$ACTIVITY)

	if [[ "$(echo $start | grep "Warning:\ Activity\ not\ started" -c)" = "1" ]]; then
		log_info "Warning: Application already running and use the current package"
		log_info "Forcing new installation..."
		run_action "deploy"
		run_action "run"
		exit

	elif [[ "$(echo $start | grep "error" -c)" = "1" ]]; then
		# show the output
		echo $start
		exit
	fi

	# show the output
	echo $start

	# activate the logs
	if [ $LOG != "false" ]; then

		log_action_separator "LOG"

		echo "Logging $PACKAGE/$PACKAGE.$ACTIVITY..."

		# clear logs
		adb logcat -c

		case $LOG in
			debug)
				adb $targetoption logcat | $PGT_DIRECTORY/tools/coloredlogcat.py
				;;
			phonegap)
				adb $targetoption logcat -v time PhoneGapLog:V *:S | $PGT_DIRECTORY/tools/coloredlogcat.py
				;;
		esac

	fi
}